title: Wladefant's Blog
description: A simple markdown based blog
baseurl: "/blog" 
url: "https://wladefant.github.io" 
github_username:  wladefant

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. 
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include in processing.
# The following items will be processed, by default. 
include:
  - _posts

# Layouts
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"