remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: Wladimir Kirjanovs
author: Wladimir Kirjanovs


navbar-links:
  Blog: "/"
  # Hire me: "https://attalitech.com/"
  Projects: "projects"
  About Me / Contact: "aboutme"
  ❤ Support: "https://github.com/sponsors/wladefant"

avatar: "/assets/img/profile-picture.jpeg"

social-network-links:
  email: "wladefant@gmail.com"
  facebook: wladefant
  github: wladefant
  twitter: wladefant
  # linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/19319169/wladefant"
  # calendly: "attalitech/meeting"
  youtube: "@wladefant"
  # patreon: DeanAttali

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "wladefant, wladimir, kirjanovs, wladimir kirjanovs"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

edit_page_button: true

timezone: "America/Toronto"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

disqus: "deanattali-site"
gtag: "G-HKWW77BNTR"
fb_app_id: "536330676521989"

url-pretty: "❤ Support"
url-canonical: https://github.com/sponsors/wladefant

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      # carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      # original: before-content: [support_promo_box.html, carbonads.html]
      before-content: [support_promo_box.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

# 2fc73a3a967e97599c9763d05e564189d5
